jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 7030
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/support #change this to your database url
    password: 12345 #change this to your database username
    username: postgres #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false